#!/usr/bin/env bash

set -eou pipefail

CLONER_HOST=localhost
CLONER_PORT=9911

# a unique name to identify the cloned emacs
CLONE_NAME=$1

# the pid of this clone-one process, which is the one your window manager would have if your window manager spawns clone-one
CLONE_WRAPPER_PID=$BASHPID

# crazy how hard this is: https://unix.stackexchange.com/questions/92978/what-does-this-2-mean-in-shell-scripting
# just trying to forward the exact command line string, minus the first arg, base64 encoded, into the babashka process
# has to support quotes, as in --eval '(message "hi")'
expand-q() { for i; do echo ${i@Q}; done; }
EMACS_ARGS=$(expand-q "${@:2}")

# base64 is used to avoid bash string escaping issues; -w0 avoids base64 default wrapping at 76 chars which would break long arg strings
EMACS_ARGS_ENC=$(printf '%s ' $EMACS_ARGS | base64 -w0)

#echo $EMACS_ARGS
#echo $EMACS_ARGS_ENC
#echo $EMACS_ARGS_ENC | base64 -d
echo "{:command :clone :name \"$CLONE_NAME\" :pid $CLONE_WRAPPER_PID :args \"$EMACS_ARGS_ENC\"}" | nc $CLONER_HOST $CLONER_PORT
